name: Weekly Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install chromium

      - name: Run pipeline
        run: python run_pipeline.py

      - name: Clone frontend repo
        run: |
         git clone https://x-access-token:${{ secrets.FRONTEND_TOKEN }}@github.com/Farahat78/MUDABER.git frontend

      - name: Copy updated data
        run: |
          cp data/latest_products.csv frontend/data/
          cp data/predictions.csv frontend/data/

      - name: Push updated files
        run: |
          cd frontend
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "Auto update data files" || echo "No changes"
          git push
